### ISSUE TITLE
Cannot start the template

### ISSUE THREAD

**Issue by OlegGulevskyy** [clerkinc/t3-turbo-and-clerk#33]
New to react-native field here
Cannot run the boilerplate just after cloning the repo and setting up the API keys.
If i don't change `dev` script and keep it as is, I run into this error
```
pnpm dev

> t3-turbo-and-clerk@ dev /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile
> turbo dev --parallel

• Packages in scope: @acme/api, @acme/db, @acme/expo, @acme/nextjs, @acme/tailwind-config
• Running dev in 5 packages
• Remote caching disabled
@acme/db:dev: cache bypass, force executing e5af5e8821955279
@acme/expo:dev: cache bypass, force executing f8bf9323f836c36e
@acme/nextjs:dev: cache bypass, force executing 154f4fdf93b3fde1
@acme/nextjs:dev:
@acme/nextjs:dev: > @acme/nextjs@0.1.0 dev /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/apps/nextjs
@acme/nextjs:dev: > pnpm with-env next dev
@acme/nextjs:dev:
@acme/expo:dev:
@acme/expo:dev: > @acme/expo@0.1.0 dev /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/apps/expo
@acme/expo:dev: > expo start --ios
@acme/expo:dev:
@acme/db:dev:
@acme/db:dev: > @acme/db@0.1.0 dev /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/packages/db
@acme/db:dev: > pnpm with-env prisma studio --port 5556
@acme/db:dev:
@acme/nextjs:dev:
@acme/nextjs:dev: > @acme/nextjs@0.1.0 with-env /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/apps/nextjs
@acme/nextjs:dev: > dotenv -e ../../.env -- "next" "dev"
@acme/nextjs:dev:
@acme/db:dev:
@acme/db:dev: > @acme/db@0.1.0 with-env /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/packages/db
@acme/db:dev: > dotenv -e ../../.env -- "prisma" "studio" "--port" "5556"
@acme/db:dev:
@acme/nextjs:dev: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
@acme/nextjs:dev: warn  - You have enabled experimental feature (transpilePackages) in next.config.mjs.
@acme/nextjs:dev: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
@acme/nextjs:dev:
@acme/db:dev: Prisma schema loaded from prisma/schema.prisma
@acme/db:dev: Prisma Studio is up on http://localhost:5556
@acme/expo:dev: Starting project at /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/apps/expo
@acme/expo:dev: Some dependencies are incompatible with the installed expo version:
@acme/expo:dev:   @shopify/flash-list@1.4.0 - expected version: 1.3.1
@acme/expo:dev:   expo-auth-session@3.7.3 - expected version: ~3.8.0
@acme/expo:dev: Your project may not work correctly until you install the correct versions of the packages.
@acme/expo:dev: Install individual packages by running npx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0
@acme/nextjs:dev: event - compiled client and server successfully in 468 ms (302 modules)
@acme/nextjs:dev: wait  - compiling...
@acme/nextjs:dev: event - compiled successfully in 35 ms (259 modules)
@acme/expo:dev: Starting Metro Bundler
@acme/expo:dev: › Opening exp://192.168.1.14:19000 on iPhone 8
@acme/expo:dev: CommandError: Input is required, but 'npx expo' is in non-interactive mode.
@acme/expo:dev: Required input:
@acme/expo:dev: > Expo Go on iPhone 8 is outdated, would you like to upgrade?
@acme/expo:dev:  ELIFECYCLE  Command failed with exit code 1.
@acme/expo:dev: ERROR: command finished with error: command (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/apps/expo) pnpm run dev exited (1)
command (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/apps/expo) pnpm run dev exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    5.524s

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```
Where the error is `Expo Go on iPhone 8 is outdated, would you like to upgrade?` weirdly enough can't get much info on Google about it.

If I do change the dev script according to the instruction, I get the following error:
```
pnpm dev

> t3-turbo-and-clerk@ dev /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile
> expo start --ios

Starting project at /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile
Error: Cannot find module 'react-native/package.json'
Require stack:
- /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/noop.js
Error: Cannot find module 'react-native/package.json'
Require stack:
- /Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/resolve-from/index.js:46:47)
    at getDefaultConfig (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/@expo/metro-config/build/ExpoMetroConfig.js:182:78)
    at Object.loadAsync (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/@expo/metro-config/build/ExpoMetroConfig.js:352:23)
    at Object.instantiateMetroAsync (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js:27:45)
    at MetroBundlerDevServer.startImplementationAsync (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js:47:87)
    at async MetroBundlerDevServer.startAsync (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/@expo/cli/build/src/start/server/BundlerDevServer.js:88:24)
    at async DevServerManager.startAsync (/Users/oleggulevskyy/Documents/dev/checkout-t3-mobile/node_modules/@expo/cli/build/src/start/server/DevServerManager.js:135:13)
 ELIFECYCLE  Command failed with exit code 1.
```
I don't udnerstand, how come react-native is missing from the project, unless the default `dev` script that runs turbo repo does some sort of transpilation and creates this package silently?
Any heads up regarding this would be appreciated.

Thanks

**Comment by OlegGulevskyy** [comment]
Found an issue, needed to go to `apps/expo` and run `expo start --ios` in there, which would allow interactive mode to update the Expo Go to required version automatically.
