### ISSUE TITLE
Error when Expo attempts to boot 

### ISSUE THREAD

**Issue by pencilcheck** [clerkinc/t3-turbo-and-clerk#35]
Clean `git clone`, followed the instructions and when getting to `pnpm dev` getting errors

```

> t3-turbo-and-clerk@ dev /project/t3-turbo-and-clerk
> turbo dev --parallel

• Packages in scope: @acme/api, @acme/db, @acme/expo, @acme/nextjs, @acme/tailwind-config
• Running dev in 5 packages
• Remote caching disabled
@acme/nextjs:dev: cache bypass, force executing 154f4fdf93b3fde1
@acme/expo:dev: cache bypass, force executing f8bf9323f836c36e
@acme/db:dev: cache bypass, force executing e5af5e8821955279
@acme/nextjs:dev:
@acme/nextjs:dev: > @acme/nextjs@0.1.0 dev /project/t3-turbo-and-clerk/apps/nextjs
@acme/nextjs:dev: > pnpm with-env next dev
@acme/nextjs:dev:
@acme/expo:dev:
@acme/expo:dev: > @acme/expo@0.1.0 dev /project/t3-turbo-and-clerk/apps/expo
@acme/expo:dev: > expo start --ios
@acme/expo:dev:
@acme/db:dev:
@acme/db:dev: > @acme/db@0.1.0 dev /project/t3-turbo-and-clerk/packages/db
@acme/db:dev: > pnpm with-env prisma studio --port 5556
@acme/db:dev:
@acme/nextjs:dev:
@acme/nextjs:dev: > @acme/nextjs@0.1.0 with-env /project/t3-turbo-and-clerk/apps/nextjs
@acme/nextjs:dev: > dotenv -e ../../.env -- "next" "dev"
@acme/nextjs:dev:
@acme/db:dev:
@acme/db:dev: > @acme/db@0.1.0 with-env /project/t3-turbo-and-clerk/packages/db
@acme/db:dev: > dotenv -e ../../.env -- "prisma" "studio" "--port" "5556"
@acme/db:dev:
@acme/expo:dev: Starting project at /project/t3-turbo-and-clerk/apps/expo
@acme/expo:dev: Some dependencies are incompatible with the installed expo version:
@acme/expo:dev:   @shopify/flash-list@1.4.0 - expected version: 1.3.1
@acme/expo:dev:   expo-auth-session@3.7.3 - expected version: ~3.8.0
@acme/expo:dev: Your project may not work correctly until you install the correct versions of the packages.
@acme/expo:dev: Install individual packages by running npx expo install @shopify/flash-list@1.3.1 expo-auth-session@~3.8.0
@acme/nextjs:dev: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
@acme/nextjs:dev: warn  - You have enabled experimental feature (transpilePackages) in next.config.mjs.
@acme/nextjs:dev: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
@acme/nextjs:dev:
@acme/expo:dev: Starting Metro Bundler
@acme/db:dev: Prisma schema loaded from prisma/schema.prisma
@acme/db:dev: Prisma Studio is up on http://localhost:5556
@acme/nextjs:dev: event - compiled client and server successfully in 955 ms (302 modules)
@acme/nextjs:dev: wait  - compiling...
@acme/nextjs:dev: event - compiled successfully in 64 ms (259 modules)
@acme/expo:dev: Error: xcrun exited with non-zero code: 2
@acme/expo:dev: An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
@acme/expo:dev: Unable to boot device because we cannot determine the runtime bundle.
@acme/expo:dev: No such file or directory
@acme/expo:dev: Error: xcrun exited with non-zero code: 2
@acme/expo:dev:     at ChildProcess.completionListener (/project/t3-turbo-and-clerk/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
@acme/expo:dev:     at Object.onceWrapper (events.js:520:26)
@acme/expo:dev:     at ChildProcess.emit (events.js:400:28)
@acme/expo:dev:     at maybeClose (internal/child_process.js:1058:16)
@acme/expo:dev:     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
@acme/expo:dev:     ...
@acme/expo:dev:     at Object.spawnAsync [as default] (/project/t3-turbo-and-clerk/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
@acme/expo:dev:     at Object.xcrunAsync (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/start/platforms/ios/xcrun.js:18:46)
@acme/expo:dev:     at simctlAsync (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/start/platforms/ios/simctl.js:233:24)
@acme/expo:dev:     at bootDeviceAsync (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/start/platforms/ios/simctl.js:166:15)
@acme/expo:dev:     at Object.bootAsync (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/start/platforms/ios/simctl.js:143:11)
@acme/expo:dev:     at action (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/start/platforms/ios/AppleDeviceManager.js:73:31)
@acme/expo:dev:     at Object.waitForActionAsync (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/utils/delay.js:18:26)
@acme/expo:dev:     at ensureSimulatorOpenAsync (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/start/platforms/ios/AppleDeviceManager.js:69:44)
@acme/expo:dev:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
@acme/expo:dev:     at async Object.resolveAsync [as resolveDeviceAsync] (/project/t3-turbo-and-clerk/node_modules/@expo/cli/build/src/start/platforms/ios/AppleDeviceManager.js:98:24)
@acme/expo:dev:  ELIFECYCLE  Command failed with exit code 1.
@acme/expo:dev: ERROR: command finished with error: command (/project/t3-turbo-and-clerk/apps/expo) pnpm run dev exited (1)
@acme/db:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
@acme/nextjs:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  ELIFECYCLE  Command failed.
@acme/db:dev:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
@acme/nextjs:dev:  ELIFECYCLE  Command failed with exit code 1.
command (/project/t3-turbo-and-clerk/apps/expo) pnpm run dev exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    5.924s

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

```

My xcrun seems fine to me, can run the command
```
xcrun --show-sdk-path                                                                                          main
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

**Comment by perkinsjr** [comment]
Hi @pencilcheck basd upon this error

```
@acme/expo:dev: Error: xcrun exited with non-zero code: 2
@acme/expo:dev: An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
@acme/expo:dev: Unable to boot device because we cannot determine the runtime bundle.
@acme/expo:dev: No such file or directory
@acme/expo:dev: Error: xcrun exited with non-zero code: 2
```

Something with the setup of your machine fails when using code.

1. Do you have a iOS simulator installed?
2. What version of Xcode are you running?
3. Can you go to the /apps/expo/ and run npm run start.

**Comment by perkinsjr** [comment]
You can probably run 

```open -a Simulator```

Then 

```pnpm run dev ```

**Comment by perkinsjr** [comment]
Closing due to this not being an issue with the template but the setup of the dev machine.

Please re open if you believe this is incorrect.

**Comment by pencilcheck** [comment]
> Hi @pencilcheck basd upon this error
> 
> ```
> @acme/expo:dev: Error: xcrun exited with non-zero code: 2
> @acme/expo:dev: An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> @acme/expo:dev: Unable to boot device because we cannot determine the runtime bundle.
> @acme/expo:dev: No such file or directory
> @acme/expo:dev: Error: xcrun exited with non-zero code: 2
> ```
> 
> Something with the setup of your machine fails when using code.
> 
> 1. Do you have a iOS simulator installed?
> 2. What version of Xcode are you running?
> 3. Can you go to the /apps/expo/ and run npm run start.

Yes
Xcode 14.2
Go to /apps/expo and run pnpm start worked. I see the QR code and stuff, no errors.

It looks like opening the simulator before running `pnpm dev` worked. Not sure what I did wrong to get xcrun not getting Simulator to be honest. However I encountered another error. Which is weird because if a template can't work out of box then I can't really recommend or use this template at all.

Will open a different ticket for this.

**Comment by perkinsjr** [comment]
to confirm this error has nothing to do with the template at all. but to do with Expo and Xcode
command line tools.

keep my eye out for the other issue.
