### ISSUE TITLE
Missing frontendApi or publishableKey only on build, not dev

### ISSUE THREAD

**Issue by evheath** [clerkinc/t3-turbo-and-clerk#48]
**Describe the bug**
After following the README of repo, I was able to successfully run the demo using `pnpm run dev` (good stuff I am very impressed!).

However building the project fails at NextJS's build step with the error "Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys." 

This seems strange since the API key is certainly working when in development mode. 

**To Reproduce**
1. Follow the README
2. Verify the API keys work by viewing posts in the demo or seeing that users populate in the Clerk dashboard
3. run `pnpm run build` from the project directory 

**Expected behavior**
A successful build; or at least to not see this particular error on build.

**Logs**
Here are the logs of the error
```
➜  t3-turbo-and-clerk git:(main) ✗ pnpm run build

> t3-turbo-and-clerk@ build /Users/elliot/code/t3-turbo-and-clerk
> turbo build

╭──────────────────────────────────────────────────────────────────────╮
│                                                                      │
│                   Update available v1.7.0 ≫ v1.7.2                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.7.2    │
│                     Run "npm i turbo" to update                      │
│                                                                      │
│     Follow @turborepo for updates: https://twitter.com/turborepo     │
╰──────────────────────────────────────────────────────────────────────╯
• Packages in scope: @acme/api, @acme/db, @acme/expo, @acme/nextjs, @acme/tailwind-config
• Running build in 5 packages
• Remote caching disabled
@acme/db:db-generate: cache bypass, force executing cdf6355d340c21fb
@acme/db:db-generate:
@acme/db:db-generate: > @acme/db@0.1.0 db-generate /Users/elliot/code/t3-turbo-and-clerk/packages/db
@acme/db:db-generate: > pnpm with-env prisma generate
@acme/db:db-generate:
@acme/db:db-generate:
@acme/db:db-generate: > @acme/db@0.1.0 with-env /Users/elliot/code/t3-turbo-and-clerk/packages/db
@acme/db:db-generate: > dotenv -e ../../.env -- "prisma" "generate"
@acme/db:db-generate:
@acme/db:db-generate: Prisma schema loaded from prisma/schema.prisma
@acme/db:db-generate:
@acme/db:db-generate: ✔ Generated Prisma Client (4.7.1 | library) to ./../../node_modules/@prisma/client in 31ms
@acme/db:db-generate: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
@acme/db:db-generate: ```
@acme/db:db-generate: import { PrismaClient } from '@prisma/client'
@acme/db:db-generate: const prisma = new PrismaClient()
@acme/db:db-generate: ```
@acme/nextjs:build: cache miss, executing 5d8b182aa6ac1530
@acme/nextjs:build:
@acme/nextjs:build: > @acme/nextjs@0.1.0 build /Users/elliot/code/t3-turbo-and-clerk/apps/nextjs
@acme/nextjs:build: > next build
@acme/nextjs:build:
@acme/nextjs:build: warn  - You have enabled experimental feature (transpilePackages) in next.config.mjs.
@acme/nextjs:build: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
@acme/nextjs:build:
@acme/nextjs:build: info  - Linting and checking validity of types...
@acme/nextjs:build:
@acme/nextjs:build: ./src/middleware.ts
@acme/nextjs:build: 5:37  Warning: '_req' is defined but never used.  @typescript-eslint/no-unused-vars
@acme/nextjs:build:
@acme/nextjs:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
@acme/nextjs:build: info  - Creating an optimized production build...
@acme/nextjs:build: info  - Compiled successfully
@acme/nextjs:build: info  - Collecting page data...
@acme/nextjs:build: info  - Generating static pages (0/5)
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:
@acme/nextjs:build: Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build: info  - Generating static pages (1/5)
@acme/nextjs:build:
@acme/nextjs:build: Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build: info  - Generating static pages (2/5)
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:
@acme/nextjs:build: Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build: info  - Generating static pages (3/5)
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:
@acme/nextjs:build: Error occurred prerendering page "/sign-in/[[...index]]". Read more: https://nextjs.org/docs/messages/prerender-error
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:
@acme/nextjs:build: Error occurred prerendering page "/sign-up/[[...index]]". Read more: https://nextjs.org/docs/messages/prerender-error
@acme/nextjs:build: Error: @clerk/nextjs: Missing frontendApi or publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@acme/nextjs:build:     at Object.throwMissingFrontendApiOrPublishableKeyError (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3142)
@acme/nextjs:build:     at ClerkProviderBase (/Users/elliot/code/t3-turbo-and-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@acme/nextjs:build:     at Wc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:     at Z (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@acme/nextjs:build:     at Zc (/Users/elliot/code/t3-turbo-and-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@acme/nextjs:build:
@acme/nextjs:build: > Build error occurred
@acme/nextjs:build: info  - Generating static pages (5/5)
@acme/nextjs:build: Error: Export encountered errors on following paths:
@acme/nextjs:build: 	/
@acme/nextjs:build: 	/_error: /404
@acme/nextjs:build: 	/_error: /500
@acme/nextjs:build: 	/sign-in/[[...index]]
@acme/nextjs:build: 	/sign-up/[[...index]]
@acme/nextjs:build:     at /Users/elliot/code/t3-turbo-and-clerk/node_modules/next/dist/export/index.js:408:19
@acme/nextjs:build:     at runMicrotasks (<anonymous>)
@acme/nextjs:build:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@acme/nextjs:build:     at async Span.traceAsyncFn (/Users/elliot/code/t3-turbo-and-clerk/node_modules/next/dist/trace/trace.js:79:20)
@acme/nextjs:build:     at async /Users/elliot/code/t3-turbo-and-clerk/node_modules/next/dist/build/index.js:1342:21
@acme/nextjs:build:     at async Span.traceAsyncFn (/Users/elliot/code/t3-turbo-and-clerk/node_modules/next/dist/trace/trace.js:79:20)
@acme/nextjs:build:     at async /Users/elliot/code/t3-turbo-and-clerk/node_modules/next/dist/build/index.js:1202:17
@acme/nextjs:build:     at async Span.traceAsyncFn (/Users/elliot/code/t3-turbo-and-clerk/node_modules/next/dist/trace/trace.js:79:20)
@acme/nextjs:build:     at async Object.build [as default] (/Users/elliot/code/t3-turbo-and-clerk/node_modules/next/dist/build/index.js:65:29)
@acme/nextjs:build:  ELIFECYCLE  Command failed with exit code 1.
@acme/nextjs:build: ERROR: command finished with error: command (/Users/elliot/code/t3-turbo-and-clerk/apps/nextjs) pnpm run build exited (1)
command (/Users/elliot/code/t3-turbo-and-clerk/apps/nextjs) pnpm run build exited (1)

 Tasks:    1 successful, 2 total
Cached:    0 cached, 2 total
  Time:    5.408s

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
➜  t3-turbo-and-clerk git:(main) ✗
```

Here are the logs of the setup as per the README
```
➜  code git clone https://github.com/evheath/t3-turbo-and-clerk.git
Cloning into 't3-turbo-and-clerk'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 105 (delta 3), reused 72 (delta 1), pack-reused 0
Receiving objects: 100% (105/105), 161.99 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (3/3), done.
➜  code cd t3-turbo-and-clerk
➜  t3-turbo-and-clerk git:(main) pnpm i
Scope: all 6 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +1397
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/elliot/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 0, reused 1263, downloaded 0, added 1397, done
➜  t3-turbo-and-clerk git:(main) cp .env.example .env
➜  t3-turbo-and-clerk git:(main) pnpm db-push

> t3-turbo-and-clerk@ db-push /Users/elliot/code/t3-turbo-and-clerk
> turbo db-push

╭──────────────────────────────────────────────────────────────────────╮
│                                                                      │
│                   Update available v1.7.0 ≫ v1.7.2                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.7.2    │
│                     Run "npm i turbo" to update                      │
│                                                                      │
│     Follow @turborepo for updates: https://twitter.com/turborepo     │
╰──────────────────────────────────────────────────────────────────────╯
• Packages in scope: @acme/api, @acme/db, @acme/expo, @acme/nextjs, @acme/tailwind-config
• Running db-push in 5 packages
• Remote caching disabled
@acme/db:db-push: cache bypass, force executing 3f0eeb4851b433fa
@acme/db:db-push:
@acme/db:db-push: > @acme/db@0.1.0 db-push /Users/elliot/code/t3-turbo-and-clerk/packages/db
@acme/db:db-push: > pnpm with-env prisma db push
@acme/db:db-push:
@acme/db:db-push:
@acme/db:db-push: > @acme/db@0.1.0 with-env /Users/elliot/code/t3-turbo-and-clerk/packages/db
@acme/db:db-push: > dotenv -e ../../.env -- "prisma" "db" "push"
@acme/db:db-push:
@acme/db:db-push: Prisma schema loaded from prisma/schema.prisma
@acme/db:db-push: Datasource "db": SQLite database "db.sqlite" at "file:./db.sqlite"
@acme/db:db-push:
@acme/db:db-push: 🚀  Your database is now in sync with your Prisma schema. Done in 22ms
@acme/db:db-push:
✔ Generated Prisma Client (4.7.1 | library) to ./../../node_modules/@prisma/clie
@acme/db:db-push: nt in 60ms
@acme/db:db-push:
@acme/db:db-push: ┌─────────────────────────────────────────────────────────┐
@acme/db:db-push: │  Update available 4.7.1 -> 4.9.0                        │
@acme/db:db-push: │  Run the following to update                            │
@acme/db:db-push: │    npm i --save-dev prisma@latest                       │
@acme/db:db-push: │    npm i @prisma/client@latest                          │
@acme/db:db-push: └─────────────────────────────────────────────────────────┘

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    2.499s
```

Here is the readout of the .env file (excluding the secret key)
```
➜  t3-turbo-and-clerk git:(main) ✗ cat .env
# Since .env is gitignored, you can use .env.example to build a new `.env` file when you clone the repo.
# Keep this file up-to-date when you add new variables to \`.env\`.

# This file will be committed to version control, so make sure not to have any secrets in it.
# If you are cloning this repo, create a copy of this file named `.env` and populate it with your secrets.

# We use dotenv to load Prisma from Next.js' .env file
# @see https://www.prisma.io/docs/reference/database-reference/connection-urls
DATABASE_URL=file:./db.sqlite

# CLERK is used for authentication and authorization in the app
# @see https://dashboard.clerk.dev for your Clerk API keys
#
### NEW KEYS FOR APPS AFTER 1/18/2023
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_bWlnaHR5LXNjb3JwaW9uLTM3LmNsZXJrLmFjY291bnRzLmRldiQ
```

**Screenshots**
Here's a screenshot demostrating the key is working for nextjs
![nextjs](https://user-images.githubusercontent.com/7056341/216663484-d1d1088c-7852-401d-b67e-660db21e0ddf.png)

Here's a screenshot demostrating the key is working for mobile
![mobile](https://user-images.githubusercontent.com/7056341/216662384-6901a224-222c-4e10-95ab-61f6360b70b0.png)

**Desktop (please complete the following information):**
 - OS: [macOS Ventura 13.1 (m1 chip)]
 - Browser [Chrome]
 - Version [Version 109.0.5414.119 (Official Build) (arm64)]

**Smartphone (please complete the following information):**
 - Device: [simulator iPhone 14 Pro Max]
 - OS: [iOS 16.2]

**Additoinal Info**
You can checkout the templated repo [here](https://github.com/evheath/t3-turbo-and-clerk)

**Comment by perkinsjr** [comment]
Hi there.

The build locally doesn't accept the env vars by default, when it is deployed this are injected by Vercel for example. If you want to build locally you need to update the build in the app/nextjs

```
 "build": "pnpm with-env next build"
 ```
Or you can create a localbuild with turbo, this is very intentional and not a bug.
