### ISSUE TITLE
Error: @clerk/nextjs: Missing publishableKey at Next.JS

### ISSUE THREAD

**Issue by indicozy** [clerkinc/t3-turbo-and-clerk#69]
**Describe the bug**

After I set my dotenv, I still get this error:
```
Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
```

I need to manually add it to ClerkProvider, is there better option?

**To Reproduce**
1. set dotenv
2. pnpm i; pnpm build
3. See error

**Expected behavior**
Build works fine

**Logs**
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
@belearn/web:build: Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@belearn/web:build:     at Object.throwMissingPublishableKeyError (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3557)
@belearn/web:build:     at ClerkProviderBase (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/clerk-react/dist/contexts/ClerkProvider.js:20:34)
@belearn/web:build:     at Wc (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@belearn/web:build:     at Zc (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@belearn/web:build:     at Z (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@belearn/web:build:     at Zc (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@belearn/web:build:     at Z (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@belearn/web:build:     at Zc (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@belearn/web:build:     at Z (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@belearn/web:build:     at Zc (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@belearn/web:build: info  - Generating static pages (3/5)
@belearn/web:build: 
@belearn/web:build: Error occurred prerendering page "/sign-up/[[...index]]". Read more: https://nextjs.org/docs/messages/prerender-error
@belearn/web:build: Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.dev/last-active?path=api-keys.
@belearn/web:build:     at Object.throwMissingPublishableKeyError (/home/indicozy/Documents/Projects/belearn-clerk/node_modules/@clerk/nextjs/node_modules/@clerk/shared/dist/index.js:1:3557)
```

**Screenshots**

System:
    OS: Linux 6.2 Fedora Linux 37 (Workstation Edition)
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 1.26 GB / 6.62 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/lts/bin/yarn
    npm: 9.3.1 - ~/.asdf/plugins/nodejs/shims/npm

**Additional context**

**Comment by perkinsjr** [comment]
Where did you place your .env? 

I cannot recreate this

**Comment by indicozy** [comment]
On the root folder, pnpm is started from root too

**Comment by indicozy** [comment]
It is still not working, I guess it's because there was some misconfiguration with pnpm to hoist env variables. DB cannot get dotenv value with `pnpm dev` but it works with `pnpm db-push`. Similarly with issue #70.

**Comment by indicozy** [comment]
#70 issue was solved by removing `dev` script in apps/expo. I guess it should be removed in the template first, since not everyone requires expo

**Comment by indicozy** [comment]
added pull request: #71

**Comment by perkinsjr** [comment]
I cannot recreate any of these issues. I just spent the morning updating the template to support Expo 48. I can both hoist the DB creds in development, the publishable key to Next.js and Clerk Secrets. 

Building is specifically set the way it is in the template as the expectation here is you are building your project on CI/CD or any other deployment service like Vercel.
